created Option screen
mobven/YummyCompose pull request #35
Opened 2024-01-04 11:18 UTC by yunusbedir-mobven

2024-01-11 15:41 UTC, esrakayamb requested changes

2024-01-11 15:41 UTC, esrakayamb commented on app/src/main/java/com/mobven/yummy/ui/screens/option/OptionScreen.kt
> +                    YummyHead1SemiBoldText(
Font semibold yokmuş, font kısmına ekleyebilir misin

2024-01-11 15:41 UTC, esrakayamb commented on app/src/main/java/com/mobven/yummy/ui/screens/option/OptionScreen.kt
> +                    CounterButton(type = CounterButtonType.BIG, counterValue) {
@tunahanbozkurt  buraya modifier gelicek, tasarımda bir büyük bir küçük hali var

2024-01-11 15:41 UTC, esrakayamb commented on designsystem/src/main/java/com/mobven/designsystem/components/chip/YummyCircleChip.kt
> +    contentPadding: PaddingValues = PaddingValues(horizontal = 10.dp),
default 0 olsun kullanırken padding istenirse verilsin

2024-01-11 15:41 UTC, esrakayamb commented on designsystem/src/main/java/com/mobven/designsystem/components/chip/YummyCircleChip.kt
> +            style = MaterialTheme.typography.h4MediumStyle,
Textlerdeki metinler ortalı görünmüyor, bunu düzeltmek için fontlara platformStyle = PlatformTextStyle(includeFontPadding = false) bunu vermeliyiz.

2024-01-11 15:41 UTC, esrakayamb commented on designsystem/src/main/java/com/mobven/designsystem/components/chip/YummyCircleChip.kt
> +fun LazyRowYummyCircleChip(
selectedChip diye bir parametre alalım, nullable olsun

2024-01-11 15:41 UTC, esrakayamb commented on app/src/main/java/com/mobven/yummy/ui/screens/option/OptionScreen.kt
> +                top = 16.dp
12.dp olcak ama en üstte kullanılan 16.dp olcak

2024-01-11 15:41 UTC, esrakayamb commented on app/src/main/java/com/mobven/yummy/ui/screens/option/OptionScreen.kt
> +                .padding(top = 16.dp)
padding 12.dp olcak

2024-01-11 15:41 UTC, esrakayamb commented on app/src/main/java/com/mobven/yummy/ui/screens/option/OptionScreen.kt
> +            horizontalArrangement = Arrangement.SpaceBetween
buna gerek yok

2024-01-11 15:41 UTC, esrakayamb commented on designsystem/src/main/java/com/mobven/designsystem/components/inputs/MultilineInputField.kt
> +                .height(96.dp),
.heightIn(min = 96.dp), bu şekilde değiştirelim

2024-01-11 15:41 UTC, esrakayamb commented on designsystem/src/main/java/com/mobven/designsystem/components/inputs/MultilineInputField.kt
> +            maxLines = 3,
bunu kaldıralım (yazdıkça genişlemesi için

2024-01-11 15:41 UTC, esrakayamb commented on designsystem/src/main/java/com/mobven/designsystem/components/inputs/MultilineInputField.kt
> +            singleLine = false,
zaten default false

2024-01-11 15:41 UTC, esrakayamb commented on designsystem/src/main/java/com/mobven/designsystem/components/inputs/MultilineInputField.kt
> +            value = value.orEmpty(),
orEmpty() gerek yok

2024-01-11 15:41 UTC, esrakayamb commented on designsystem/src/main/java/com/mobven/designsystem/components/inputs/MultilineInputField.kt
> +    keyboardType: KeyboardType = KeyboardType.Ascii,
keyboardType parametreden kullanmaya gerek yok

2024-01-11 15:41 UTC, esrakayamb commented on app/src/main/java/com/mobven/yummy/ui/screens/option/OptionScreen.kt
> +                            top = 24.dp,
horizontal ve vertical'ıda kapsayan custom modifier yazalım

2024-02-08 14:34 UTC, abalta approved these changes

2024-02-08 14:34 UTC, merged